version: '3'

services:
  task-dashboard:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend API
    volumes:
      - task_data:/app/data
    env_file:
      - .env.production
    # environment:
      # For production MySQL, override these in environment or .env file:
      # - DB_TYPE=mysql
      # - DB_HOST=your_mysql_host
      # - DB_PORT=3306
      # - DB_USER=your_mysql_user
      # - DB_PASSWORD=your_mysql_password
      # - DB_NAME=your_database_name

volumes:
  task_data: